name: BountyHunters
version: ${project.version}
main: net.Indyuce.bountyhunters.BountyHunters
author: Indyuce
depend: [Vault]
commands:
    addbounty:
        description: Set a bounty on a player.
        aliases: [bounty, setbounty]
    bounties:
        description: See all the active bounties.
    hunters:
        description: Opens the hunter leaderboard.
        aliases: [hunterleaderboard,hunterlb]
permissions:
    bountyhunters.list:
        default: op
    bountyhunters.admin:
        default: op
    bountyhunters.leaderboard:
        default: op
    bountyhunters.add:
        default: op
    bountyhunters.title:
        default: op
    bountyhunters.quote:
        default: op
    bountyhunters.claim:
        default: op
    bountyhunters.immunity.bypass:
        default: false
    bountyhunters.immunity:
        default: false
    bountyhunters.untargetable:
        default: false
    bountyhunters.untargetable.bypass:
        default: false
    bountyhunters.update-notify:
        default: op